# Generated by Django 4.2.1 on 2023-10-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_patient",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_expert",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
