# Generated by Django 4.2.6 on 2023-10-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0003_alter_customuser_is_expert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
